server {
    listen 80;
    server_name api.richbest.cn;

    location ^~ /.well-known/acme-challenge/ {
        resolver 127.0.0.11 valid=10s ipv6=off;
        set $acme_upstream http://api-certbot-challenge:80;
        proxy_pass $acme_upstream$request_uri;
        proxy_set_header Host $host;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}
